### ISSUE TITLE
Issue with getBuildNumberInt - not taking dot into consideration

### ISSUE THREAD

**Issue by slawkens** [Mistralys/version-parser#2]
Hi,

first off - thanks for your package - it is very useful.

I encountered a problem with the function getBuildNumberInt()

Both of those versions returns the same number:
5.0-beta - 4999999000101
5.0-beta.2 - 4999999000101

If I change **5.0-beta.2** to **5.0-beta2** (without the dot) then it's working as expected. So the problem is with "dot".

5.0-beta.2, is however - according to this answer - also a valid version:
https://stackoverflow.com/questions/51373151/releasing-alpha-to-beta-to-production-with-semver

**Comment by Mistralys** [comment]
Hi @slawkens, thanks for the report - I will have a look.

**Comment by Mistralys** [comment]
Hi @slawkens, please test it with the new release:

https://github.com/Mistralys/version-parser/releases/tag/2.1.0

**Comment by slawkens** [comment]
Hi,

Thanks, it works!

**Comment by slawkens** [comment]
Hi,

is it possible to do the otherwise? From number into version?

Like I have following number: 6000000000000

And I would like to convert it into 6.0.

Couldn't find a method for this, is it possible?

**Comment by Mistralys** [comment]
Hi slawkens,

Converting the build numbers back to version strings should be possible in principle. May I ask why you need this? The build numbers are practical to work with, but they are not intended to be used as the primary version information. 

For example, if I were  to store a version in a database, I would always include both the build number (for easy sorting) and the original version string.

**Comment by slawkens** [comment]
Hi,

you probably know laravel? That's the framework I'm using in my project.

That's the code piece I did. As you say I do the same - I save both version, and version_as_number in database.

This is the query:
```
->orderBy('downloads', 'DESC')
            ->groupBy('name')
            ->select(['plugins.id', 'plugins.name', 'author', 'description', DB::raw('SUM(downloads) as downloads'),
                DB::raw('MAX(version_as_number) as version_as_number'),
                'plugins.updated_at', 'plugins.created_at', 'user_id'])
            ->get();
```

I select latest version_sa_number, because with only plain version like 6.0 and beta, rc, etc. it won't sort correctly (well, mysql).

And this query won't deliver me the plain version. Only version_as_number.

I did a workaround for this, where I manually loop over the results, and fetch version again.

```
foreach ($rows as $row) {
            $row->version = Plugin::where('name', $row->name)->where('version_as_number', $row->version_as_number)->first()->version;
        }
```

This is not a best-optimised approach, when man has like me over 80 records. But I cache it, so I kinda don't notice.

That's why I asked about backward way. As I only had the version_as_number.

Anyway, mine problem is with this approach, solved.

Wish you happy new year!

That's my website (yeah, self-promotion) :P :: https://plugins.my-aac.org

**Comment by Mistralys** [comment]
Hi @slawkens, happy new year to you too! I'm glad to hear that you were able to solve the issue.

Could you not make a join in your query to fetch the information directly in a single query?

And nice website - you have some cool plugins listed there :D

**Comment by slawkens** [comment]
Hi,

thanks. Ye currently its a repository of plugins for AAC (kinda like CMS) for a game called Open Tibia, but the themes listed there can be used for other purposes. I will be changing it soon to general CMS, so it can be used on any website, and not just this particular game.

Regards,
